plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mekromn.betterpicker'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mekromn.betterpicker'
        minSdk 30
        targetSdk 35
        versionCode 4
        versionName '0.2.2'
    }

    signingConfigs {
        stableDebug {
            storeFile file(System.getProperty('user.home') + '/.android/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.stableDebug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
